classes:
  - name: "rajadura"
    critical: true
  - name: "mancha_azul"
    critical: true
  - name: "haz_honeycomb"
    critical: true
  - name: "nudo_hueco"
    critical: true
  - name: "honeycomb"
    critical: true
#  - name: "mancha_aff"
#    critical: true
#  - name: "mancha_af"
#    critical: true
#  - name: "hueco_polilla"
#    critical: true
#  - name: "corcho_gran_frac"
#    critical: true
#  - name: "corcho_gran_nofrac"
#    critical: true
#  - name: "sheck_ecu"
#    critical: true
#  - name: "sombra_nudo"
#    critical: true
#  - name: "nudo_sano"
#    critical: true
#  - name: "nudillo"
#    critical: true
#  - name: "ojo_pajaro"
#    critical: true
#  - name: "podredumbre"
#    critical: true
#  - name: "corazon"
#    critical: true
#  - name: "others"
#    critical: false